config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => {:registrations => :registrations}

  root 'welcome#index'
  resources :contacts, only: [:index, :create]
  get '/promotion' => 'welcome#promotion', as: :promotion

  get '/artists/:category/:subcategory' => 'artist#index', as: :artists_profile
  get '/profile' => 'artist#profile', as: :profile
  get '/profile/:id' => 'artist#promotion', as: :promotion_profile
  get '/load_subcategory/:category_id' => 'artist#load_subcategory', as: :load_subcategory
  resources :subscriptions, only: [:new, :create, :destroy]
  get '/search' => 'welcome#search'

  resources :events

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-bg-box">
    <h1 class="lead-text">New Artist Release</h1>
    <ul class="menu">
      <li>
        <%= link_to 'Home', root_path %>
      </li>
      <li>
        <%= link_to 'About Us', root_path %>
      </li>
      <li>
        <%= link_to 'Contact', root_path %>
      </li>
    </ul>
    <p>
      Dallas, TX, 75228
    </p>

    <p>
      info@newartistrelease.com
    </p>

    <p>
      Copyright &copy; 2016 <%= link_to 'Web Site Design', '#' %> by ugl.com group, Inc
    </p>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="main-menu">
  <ul>
    <li>
      <%= link_to 'Home', root_path %>
    </li>
    <li>
      <%= link_to 'Promotion', promotion_path %>
    </li>
    <% Category.top_categories.each do |cat| %>
        <li class="dropdown">
          <a href="#"><%= cat.name %></a>
          <ul class="dropdown-content">
            <% cat.sub_categories.each do |scat| %>
                <li>
                  <%= link_to scat.name, artists_profile_path(cat.name.downcase, scat.name.downcase) %>
                </li>
            <% end %>
          </ul>
        </li>
    <% end %>
    <li>
      <%= link_to 'Contact Us', contacts_path %>
    </li>
    <% if current_user.present? %>
        <li>
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
        </li>
        <li>
          <%= link_to 'Events', events_path %>
        </li>
        <li>
          <%= link_to 'Profile', profile_path %>
        </li>
    <% else %>
        <li> <%= link_to 'LogIn', new_user_session_path %> </li>
        <li> <%= link_to 'SignUp', new_user_registration_path %> </li>
    <% end %>
    <li id="site-search">
      <form class="form-wrapper" action="/search" method="get">
        <input type="text" name='search' placeholder="Search here...">
        <button type="submit">Search</button>
      </form>
    </li>
  </ul>
  <div style="clear: both;"></div>
</div>

app/views/shared/_validation_error.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>