config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => {:registrations => :registrations}

  root 'welcome#index'
  resources :contacts, only: [:index, :create]
  get '/promotion' => 'welcome#promotion', as: :promotion

  get '/artists/:category/:subcategory' => 'artist#index', as: :artists_profile
  get '/profile' => 'artist#profile', as: :profile
  get '/profile/:id' => 'artist#promotion', as: :promotion_profile
  get '/load_subcategory/:category_id' => 'artist#load_subcategory', as: :load_subcategory
  resources :subscriptions, only: [:new, :create, :destroy]
  get '/search' => 'welcome#search'

  resources :events

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :image, EventUploader
  belongs_to :user
  validates_presence_of :title, :location, :date
  extend FriendlyId
  friendly_id :title, use: :slugged

  def short_address
    if country.present? && state.present?
      "#{country}, #{state}"
    elsif country.present?
      country
    elsif state.present?
      state
    else
      long_address
    end
  end

  def long_address
    location
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: :show

  def index
    @events = current_user.events.order('id desc')
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.friendly.find(params[:id])
    @artist = @event.user
  end

  def edit
    @event = current_user.events.friendly.find(params[:id])
  end

  def update
    @event = current_user.events.find_by_id(params[:id])
    if @event.update_attributes(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    event = current_user.events.find_by_id(params[:id])
    event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit!
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="event-date">
  <div class="date">
    <span class="day"> <%= event.date.strftime('%d') %> </span>
    <span class="month"> <%= event.date.strftime('%B') %> </span>
  </div>
</div>
<div class="event-item-details">
  <% if current_user.present? && event.user_id == current_user.id %>
      <div class="event-actions">
        <%= link_to edit_event_path(event) do %>
            <i class="fa fa-pencil"> </i>
        <% end %>

        <%= link_to event_path(event), method: 'delete', data: {confirm: 'Are you sure?'} do %>
            <i class="fa fa-times"> </i>
        <% end %>
      </div>
  <% end %>
  <h3 class="reset-top-margin"> <%= link_to event.title, event, class: 'event-link' %> </h3>

  <p>
    <%= raw truncate(event.description, length: 150, omission: '...') %>
  </p>
</div>

app/views/events/_form.html.erb
<div class="panel-body">
  <div class="event-form">
    <%= form_for @event do |f| %>
        <%= render 'shared/validation_error', object: @event %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :location, 'Location' %>
          <%= f.text_field :location, class: 'form-control' %>
          <%= f.hidden_field :lat %>
          <%= f.hidden_field :lng %>
          <%= f.hidden_field :country %>
          <%= f.hidden_field :state %>
        </div>

        <div class='form-group'>
          <%= f.label :date, "Date & Time" %>
          <div class="input-group date">
            <%= f.text_field :date, class: 'form-control' %>
            <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar fa fa-calendar"></span>
          </span>
          </div>
        </div>

        <div class="clearfix">
          <div class="fileUpload btn btn-info pull-right">
            <span>
              <i class="fa fa-upload"></i> <%= f.object.image_url.present? ? 'Update Event Cover Image' : 'Upload Event Cover Image' %>
            </span>
            <%= f.file_field :image, autofocus: true, :class => 'form-control input_field upload' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control tinymce' %>
        </div>

        <div class="form-group clearfix">
          <%= f.submit class: 'btn btn-default pull-right' %>
        </div>

    <% end %>
  </div>
</div>

<script type="text/javascript">
    $(function () {
        $('#event_date').datetimepicker({
            format: 'Y-MM-DD HH:mm'
        });
    });

    var autocomplete;
    function init_autocomplete() {
        var input = (document.getElementById('event_location'));
        var location = {
            lat: <%= @event.lat.present? ? @event.lat : 0 %>,
            lng: <%= @event.lng.present? ? @event.lng : 0 %>
        };
        var options = {
            location: location
        };
        autocomplete = new google.maps.places.Autocomplete(input, options);
        autocomplete.addListener('place_changed', get_place);
    }

    function get_place() {
        var place = autocomplete.getPlace();
        console.log(place);
        var lat = place.geometry.location.lat();
        var lng = place.geometry.location.lng();
        $("#event_lat").val(lat);
        $("#event_lng").val(lng);
        var components = place.address_components;
        for (i = 0; i < components.length; i++) {
            types = components[i].types;
            if (types[0] == 'locality') {
                $('#event_state').val(components[i].long_name);
            }
            else if (types[0] == 'country') {
                $('#event_country').val(components[i].short_name);
            }
        }
    }

    function noSubmitOnReturn(e) {
        if (e.keyCode == 13) {
            return false;
        }
    }

    $(document).ready(function () {
        tinyMCE.init({
            selector: ".tinymce",
            menubar: false,
            height: "225",
            plugins: [
                'advlist autolink link lists print preview hr anchor pagebreak spellchecker',
                'searchreplace visualblocks visualchars code fullscreen insertdatetime nonbreaking',
                'save table emoticons template paste textcolor code anchor '
            ],
            toolbar1: 'undo redo | styleselect | fontselect | fontsizeselect bold underline italic | link image media | forecolor backcolor table | emoticons'
        });
    });


</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD-m1XVD7c3PfBX_oxxKijOqeyNNqOSUW0&libraries=places&callback=init_autocomplete" async defer></script>

app/views/events/edit.html.erb
<div class="custom-background">
  <div class="site-content-wrapper clearfix">
    <div class="event-wrapper">
      <div class="panel panel-default">
        <div class="panel-heading"> Edit Event</div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="site-content-wrapper clearfix">
  <div class="event-wrapper">
    <div class="events clearfix">
      <%= link_to 'New Event', new_event_path, class: 'btn btn-default pull-right' %>
    </div>
    <div class="event-lists">
      <ul>
        <% @events.each do |event| %>
            <li>
              <%= render event %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="custom-background">
  <div class="site-content-wrapper clearfix">
    <div class="event-wrapper">
      <div class="panel panel-default">
        <div class="panel-heading"> Create a new event</div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container artist-promotion">
  <div class="bg-gray">
    <div class="col-lg-12 row">
      <div class="col-md-8">
        <div class="bio-content events-details-wrapper">
          <h1 class="main-title"> <%= @event.title %> </h1>
          <ul class="meta clearfix">
            <li class="date">
              <i class="icon fa fa-calendar"></i> <%= @event.date.strftime('%B %d, %Y') %>
            </li>
            <li><a href="#">
              <i class="icon fa fa-map-marker"></i> <%= @event.short_address %> </a>
            </li>
          </ul>
          <div class="event-details-image">
            <%= image_tag(@event.image_url.present? ? @event.image_url(:cover) : 'slider1.jpg') %>
          </div>
          <h3 class="main-title">Whats About</h3>

          <div class="event-content">
            <%= raw @event.description %>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="event-content-info">
          <div id="floating-form">
            <div class="section no-border">
              <div id="map_canvas"></div>
              <h3 class="main-title"><i class="fa fa-clock-o"></i> Event CountDown </h3>

              <div class="clock"></div>
              <div class="message"></div>
              <div class="main-title">
                <i class="fa fa-map-marker"></i> Event Location
              </div>
              <p>
                <%= @event.location %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    $(function () {
        var options = {
            zoom: 13,
            center: new google.maps.LatLng(<%= @event.lat.present? ? @event.lat : 30.3 %>, <%= @event.lng.present? ? @event.lng : 0 %>),
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        map = new google.maps.Map(document.getElementById('map_canvas'), options);

        var infowindow = new google.maps.InfoWindow();
        var marker, i;

        marker = new google.maps.Marker({
            position: new google.maps.LatLng(<%= @event.lat.present? ? @event.lat : 30.3 %>, <%= @event.lng.present? ? @event.lng : 0 %>),
            map: map
        });

        google.maps.event.addListener(marker, 'click', (function (marker, i) {
            return function () {
                content = "<p>" + '<%= @event.title %>' + "</p>";
                content += "<p class='map-link'>" + '<%= @event.location %>' + "</p>";
                infowindow.setContent(content);
                infowindow.open(map, marker);
            }
        })(marker, i));
    });

    $(function () {
        var clock;

        $(document).ready(function () {
            var clock;

            clock = $('.clock').FlipClock({
                clockFace: 'DailyCounter',
                autoStart: false,
                callbacks: {
                    stop: function () {
                        $('.message').html('Event date is over')
                    }
                }
            });

            clock.setTime(<%= @event.date.to_i / 800 %>);
            clock.setCountdown(true);
            clock.start();

        });
    });
</script>
<script src="https://maps.google.com/maps/api/js?key=AIzaSyD-m1XVD7c3PfBX_oxxKijOqeyNNqOSUW0"></script>