config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => {:registrations => :registrations}

  root 'welcome#index'
  resources :contacts, only: [:index, :create]
  get '/promotion' => 'welcome#promotion', as: :promotion

  get '/artists/:category/:subcategory' => 'artist#index', as: :artists_profile
  get '/profile' => 'artist#profile', as: :profile
  get '/profile/:id' => 'artist#promotion', as: :promotion_profile
  get '/load_subcategory/:category_id' => 'artist#load_subcategory', as: :load_subcategory
  resources :subscriptions, only: [:new, :create, :destroy]
  get '/search' => 'welcome#search'

  resources :events

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/controllers/artist_controller.rb
class ArtistController < ApplicationController
  # before_action :subscribed_user, only: :profile
  protect_from_forgery except: :load_subcategory

  def index
    @sub_category = Category.where('lower(name) = ?', params[:subcategory].downcase).first
    @artists = @sub_category.approved_profiles
  end

  def profile
    @resource = current_user
    @resource.profile_pictures.build
  end

  def promotion
    @artist = User.friendly.find(params[:id])
    if @artist.is_approved
      @events = @artist.events
    else
      redirect_to root_path
    end
    options = {
        title: "New Artist Release Profile #{@artist.full_name}",
        description: "#{@artist.bio.html_safe}",
        image: @artist.profile_image
    }
    prepare_meta_tags(options)
  end

  def load_subcategory
    category = Category.find_by_id(params[:category_id])
    @subcategories = category.sub_categories
  end

end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/views/artist/_subcategory_option.html.erb
<%= label_tag :sub_category_id, "Specialization area" %><br/>
<%= select_tag "user[sub_category_id]", options_for_select(@subcategories.collect { |u| [u.name, u.id] }, :selected => current_user.sub_category.present? ? current_user.sub_category : ''), {:class => "form-control"} %>

app/views/artist/index.html.erb
<div class="site-content-wrapper">
  <div class="artist-header">
    Artist <i class="fa fa-angle-double-right"></i> <%= params[:category] %>
    <i class="fa fa-angle-double-right"></i> <%= params[:subcategory] %>
  </div>

  <div class="promotion-profile reset-padding artists-list">
    <ul class="row featured-profile-list">
      <% @artists.each do |artist| %>
          <li class="col-md-4">
            <%= link_to promotion_profile_path(artist.slug) do %>
                <div class="info-container <%= artist.category.name.downcase if artist.category.present? %>-bg">
                  <div class="main-img" style="background:url(<%= image_url(artist.profile_image) %>) center center no-repeat; background-size:cover;"></div>
                  <h1 class="text-centered"><%= artist.full_name %></h1>

                  <h2 class="subheader text-centered"><%= artist.category.name %>, <%= artist.sub_category.name %></h2>

                  <h2 class="subheader text-centered"><%= artist.city %>, <%= artist.estate %></h2>

                  <div class="bio">
                    <%= raw truncate(artist.bio, length: 200) %>
                    <div class="rate-list">
                      <div class="rate-item clearfix">
                        <div class="label">Track</div>
                        <div class="value">
                          <%= artist.sub_category.name %>, <%= artist.category.name %>
                        </div>
                      </div>
                      <div class="rate-item clearfix">
                        <div class="label"> Experience</div>
                        <div class="value">
                          <% if artist.category.name.downcase == 'music' %>
                              <%= artist.how_long_play %>
                          <% elsif artist.category.name.downcase == 'models' %>
                              <%= artist.how_long_perform %>
                          <% else %>
                              <%= artist.how_long_write %>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
            <% end %>
          </li>
      <% end %>
      <% unless @artists.present? %>
          <li class="no-artist-found text-center"> No artist found :(</li>
      <% end %>
    </ul>
  </div>
</div>

app/views/artist/load_subcategory.js.erb
$('.sub_category').html("<%= escape_javascript(render 'subcategory_option').html_safe %>");

app/views/artist/profile.html.erb
<%= render 'devise/registrations/profile_edit'  %>

app/views/artist/promotion.html.erb
<div class="container artist-promotion">
  <div class="bg-gray">
    <div class="col-lg-12 row">
      <div class="col-md-8">
        <div class="bio-content">

          <div class="bio-box <%= @artist.category.name.downcase if @artist.category.present? %>-bg">
            <div style="background:url('<%= asset_path(@artist.profile_image) %>') center center no-repeat; background-size:cover;" class="main-img">&nbsp;</div>
            <h1 class=""> <%= @artist.full_name %> </h1>

            <h2 class="subheader"><%= @artist.category.name %>, <%= @artist.sub_category.name %></h2>

            <h2 class="subheader"><%= @artist.estate %>, <%= @artist.city %>, <%= @artist.country %></h2>

            <div class="social-info">
              <a class="facebook-likes" href="javascript:void(0);">
                <i class="fa fa-facebook-square"></i>
                <span data-fb-id="barnproductions" class="facebook-like-count"><%= facebook_likes(promotion_profile_url(@artist)) %></span>
                Likes
              </a>
            </div>
          </div>

          <div class="box-container">

            <div class="bio-section">
              <h2 class="reset-top-padding">ABOUT</h2>

              <div class="content">
                <%= raw @artist.bio %>
              </div>

              <div class="bio-section row clearfix" style="margin-top: 10px">
                <div class="col-lg-6">
                  <div class="content">
                    <span style="font-size: 16px;"> <%= "#{@artist.estate}, #{@artist.city}" %> </span> <br/>
                    <%= @artist.address %>
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="artist-events">
                    <h4> Events </h4>
                    <ul>
                      <% @events.each do |event| %>
                          <li class="clearfix">
                            <div class="pull-left">
                              <div> <%= link_to truncate(event.title, length: 35, omission: '...'), event_path(event.slug) %> </div>
                              <span class="profile-event-address"> <i class="fa fa-map-marker"></i> <%= event.short_address %> </span>
                            </div>
                            <div class="pull-right">
                              <div> <%= event.date.strftime('%a') %> </div>
                              <span style="color: #aaaaaa;"> <%= event.date.strftime('%B, %d') %> </span>
                            </div>
                          </li>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
            </div>

          </div>

          <div class="image-gallery">
            <div class="portfolio-title white-title" style="color: #444444;">
              Portfolio Item
            </div>

            <ul class="row gallery clearfix flexslider">
              <%# @artist.profile_pictures.each do |picture| %>
              <li class="col-lg-2 col-md-4 col-sm-3 col-xs-4 col-xxs-12 bspHasModal" data-bsp-li-index="0">
                <%= link_to image_url('photodune-514834-touchscreen-technology-xs.jpg'), rel: 'prettyPhoto[pp_gal]' do %>
                    <%= image_tag('photodune-514834-touchscreen-technology-xs.jpg') %>
                <% end %>
                <%#= link_to picture.image_url(:slider), rel: 'prettyPhoto[pp_gal]', title: 'Portfolio sample' do %>
                <%#= image_tag(picture.image_url(:large), class: 'img-responsive') %>
                <%# end %>
              </li>
              <li class="col-lg-2 col-md-4 col-sm-3 col-xs-4 col-xxs-12 bspHasModal" data-bsp-li-index="0">
                <%= link_to image_url('photodune-461673-retro-party-xs.jpg'), rel: 'prettyPhoto[pp_gal]' do %>
                    <%= image_tag('photodune-461673-retro-party-xs.jpg') %>
                <% end %>
              </li>
              <li class="col-lg-2 col-md-4 col-sm-3 col-xs-4 col-xxs-12 bspHasModal" data-bsp-li-index="0">
                <%= link_to image_url('promotion-slider.jpg'), rel: 'prettyPhoto[pp_gal]' do %>
                    <%= image_tag('promotion-slider.jpg') %>
                <% end %>
              </li>
              <%# end %>
            </ul>
          </div>

        </div>
      </div>
      <div class="col-md-4">
        <div class="bio-content-info">
          <div id="floating-form">

            <div class="section no-border">
              <div class="section-title">INFORMATION</div>

              <ul class="info-list">
                <li class="cf">
                  <div class="item">Track</div>
                  <div class="rate"><%= @artist.category.name %></div>
                </li>
                <li class="cf">
                  <div class="item">Area of Specialization</div>
                  <div class="rate"> <%= @artist.sub_category.name %> </div>
                </li>
                <% if @artist.category.name.downcase == 'music' %>
                    <% if @artist.band.downcase == 'band' %>
                        <li>
                          <div class="item">Instrument Played and/or Vocalist</div>
                          <div class="rate"> <%= @artist.role %> </div>
                        </li>
                        <li>
                          <div class="item">Years of Experience</div>
                          <div class="rate"> <%= @artist.how_long_play %> </div>
                        </li>
                    <% else %>
                        <li>
                          <div class="item">What Play</div>
                          <div class="rate"> <%= @artist.what_play %> </div>
                        </li>
                    <% end %>
                <% elsif @artist.category.name.downcase == 'models' %>
                    <li>
                      <div class="item">Years of Experience</div>
                      <div class="rate"> <%= @artist.how_long_perform %> </div>
                    </li>
                    <li>
                      <div class="item">Age</div>
                      <div class="rate"> <%= @artist.age %> Years</div>
                    </li>
                <% elsif @artist.category.name.downcase == 'books' %>
                    <li>
                      <div class="item">How long have long writing</div>
                      <div class="rate"> <%= @artist.how_long_write %> </div>
                    </li>
                <% end %>
              </ul>

            </div>

            <div class="section contact-button-container">
              <div class="button-row">
                <a class="btn btn-warning" href="#">CONTACT <%= @artist.first_name.upcase %></a>
              </div>
            </div>


            <div class="section">
              <div class="button-row">
                <a class="btn btn-info btn-large twitter twitter-share-button" href="http://www.twitter.com/share?url=<%= promotion_profile_url(@artist) %>">
                  <i class="fa fa-twitter"></i> Share On Twitter
                </a>
                <a class="btn btn-info" href="https://www.facebook.com/sharer/sharer.php?u=<%= promotion_profile_url(@artist) %>"><i class="fa fa-facebook"></i>
                  Share On Facebook
                </a>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.6.8-fix/jquery.nicescroll.min.js"></script>
<script type="text/javascript">
    $(function () {
        $("a[rel^='prettyPhoto']").prettyPhoto({autoplay_slideshow: false, social_tools: '', show_title: ''});
        $(".artist-events ul").niceScroll();
    });
</script>