config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => {:registrations => :registrations}

  root 'welcome#index'
  resources :contacts, only: [:index, :create]
  get '/promotion' => 'welcome#promotion', as: :promotion

  get '/artists/:category/:subcategory' => 'artist#index', as: :artists_profile
  get '/profile' => 'artist#profile', as: :profile
  get '/profile/:id' => 'artist#promotion', as: :promotion_profile
  get '/load_subcategory/:category_id' => 'artist#load_subcategory', as: :load_subcategory
  resources :subscriptions, only: [:new, :create, :destroy]
  get '/search' => 'welcome#search'

  resources :events

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user

  def self.subscription_plans
    {
        'Regular Subscription' => 99,
        'Additional Services: EPK (Electronic Press Kit)' => 59
    }
  end

  def self.get_stripe_plan_from_value(subscription)
    case subscription
      when 9900
        'Regular_Subscription'
      when 45900
        'EPK_Subscription'
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def new

  end

  def create
    if params[:plan].present?
      stripe_plan_name = Subscription.get_stripe_plan_from_value(params[:plan].to_i)
    else
      flash[:error] = "Something went wrong. Please contact us."
      redirect_to new_subscription_path
    end

    customer = Stripe::Customer.create(
        :email => current_user.email,
        :description => 'New Artist Release Yearly Subscription',
        :card => params[:stripeToken],
        :plan => stripe_plan_name,
        :coupon => params[:coupon]
    )


  rescue Stripe::StripeError => e
    flash[:error] = e.message
    redirect_to new_subscription_path
  else
    c = Subscription.new
    c.user_id = current_user.id
    c.stripe_id = customer.id
    c.amount = params[:plan].to_i / 100
    c.plan = stripe_plan_name
    if c.save
      redirect_to profile_path
    else
      flash[:error] = "Something went wrong. Please try again"
      redirect_to new_subscription_path
    end

  end

  def destroy

  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/new.html.erb
<script src="https://checkout.stripe.com/checkout.js"></script>


<script>
    $(document).ready(function () {
        var handler = StripeCheckout.configure({
            key: '<%= ENV['PUBLISHABLE_KEY'] %>',
            token: function (token) {
                // Use the token to create the charge with a server-side script.
                // You can access the token ID with `token.id`
                var $input = $('<input type=hidden name=stripeToken />').val(token.id);
                $('form').append($input).submit();
            }
        });

        $('#payment_btn').on('click', function (e) {
            // Open Checkout with further options
            var amount = $(".subscription-plans input[type=radio]:checked").val();
            $('#silvrback_plan').val(amount);
            handler.open({
                name: 'Silvrback Subscription',
                description: 'Annual Membership',
                email: "<%= current_user.email %>",
                amount: amount //2999
            });
            e.preventDefault();
        });

        // Close Checkout on page navigation
        $(window).on('popstate', function () {
            handler.close();
        });

    });
</script>

<div class="container subscription-wrapper">
  <h1 class="admin_header_title">Artist Release Subscription</h1>

  <h3 class="site_subtitle">
    <i>Lean, beautiful and distraction feature</i>
  </h3>

  <div class="customize_page_box">
    <h1 style="margin:0;">
      Select Your Subscription Plan
    </h1>

    <ul class="subscription-plans">
      <% Subscription.subscription_plans.each do |key, value| %>
          <li>
            <label>
              <input type="radio" name="plan_amount" value="<%= value * 100 %>" checked>
              <%= key %> –
              US$<%= value %>/Year
            </label>
          </li>
      <% end %>
    </ul>


    <div class="checkout-btn">
      <a href="javascript:void(0)" class="card-btn" id="payment_btn">
        <span>Subscribe with your Credit Card</span>
        <%= image_tag('card-img.png') %>
      </a>
    </div>


    <%= form_tag subscriptions_path, :id => 'card_submit' do %>
        <!-- default value is annual subscription -->
        <input type="hidden" name="plan" id="silvrback_plan"/>
    <% end %>
  </div>
</div>